---
driver:
  name: vagrant
  require_chef_omnibus: 12.13.37
  network:
    - ["private_network", {ip: "192.168.34.34"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[awesome_customers_ubuntu::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      awesome_customers_ubuntu:
        database:
          root_password: 'mysql_root_password'
          admin_password: 'mysql_admin_password'
